AWSTemplateFormatVersion: 2010-09-09

Description: |
  This template creates an AWS OIDC provider resource specifically for
  GitLab.

  One instance of this should be deployed per account where we want to
  establish a trust relationship - primarily so specific pipelines can
  assume a specific AWS role.

Metadata:
  stack:
    deployed_at: "{{ deploy.timestamp }}"
    deployed_with: "{{ deploy.deployed_with }}"
    version:
      template_commit: "{{ deploy.template_sha }}"
      template_ref: "{{ deploy.template_ref }}"
      config_commit: "{{ deploy.config_sha }}"
      config_ref: "{{ deploy.config_ref }}"

Resources:
  GitlabOidcProvider:
    Type: AWS::IAM::OIDCProvider
    Properties:
      Url: https://gitlab.com
      ClientIdList:
        - https://gitlab.com
      # !!! Note: This expires in 2025
      ThumbprintList: [b3dd7606d2b5a8b4a13771dbecc9ee1cecafa38a]

Outputs:
  OidcArn:
    Value: !Ref GitlabOidcProvider

